// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: mafia.proto

package mafia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MafiaRole int32

const (
	MafiaRole_UNKNOWN  MafiaRole = 0
	MafiaRole_MAFIA    MafiaRole = 1
	MafiaRole_CIVILIAN MafiaRole = 2
	MafiaRole_SHERIFF  MafiaRole = 3
)

// Enum value maps for MafiaRole.
var (
	MafiaRole_name = map[int32]string{
		0: "UNKNOWN",
		1: "MAFIA",
		2: "CIVILIAN",
		3: "SHERIFF",
	}
	MafiaRole_value = map[string]int32{
		"UNKNOWN":  0,
		"MAFIA":    1,
		"CIVILIAN": 2,
		"SHERIFF":  3,
	}
)

func (x MafiaRole) Enum() *MafiaRole {
	p := new(MafiaRole)
	*p = x
	return p
}

func (x MafiaRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MafiaRole) Descriptor() protoreflect.EnumDescriptor {
	return file_mafia_proto_enumTypes[0].Descriptor()
}

func (MafiaRole) Type() protoreflect.EnumType {
	return &file_mafia_proto_enumTypes[0]
}

func (x MafiaRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MafiaRole.Descriptor instead.
func (MafiaRole) EnumDescriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{0}
}

type MafiaState int32

const (
	MafiaState_ALIVE MafiaState = 0
	MafiaState_DEAD  MafiaState = 1
)

// Enum value maps for MafiaState.
var (
	MafiaState_name = map[int32]string{
		0: "ALIVE",
		1: "DEAD",
	}
	MafiaState_value = map[string]int32{
		"ALIVE": 0,
		"DEAD":  1,
	}
)

func (x MafiaState) Enum() *MafiaState {
	p := new(MafiaState)
	*p = x
	return p
}

func (x MafiaState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MafiaState) Descriptor() protoreflect.EnumDescriptor {
	return file_mafia_proto_enumTypes[1].Descriptor()
}

func (MafiaState) Type() protoreflect.EnumType {
	return &file_mafia_proto_enumTypes[1]
}

func (x MafiaState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MafiaState.Descriptor instead.
func (MafiaState) EnumDescriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{1}
}

type GetWaitingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetWaitingRequest) Reset() {
	*x = GetWaitingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWaitingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWaitingRequest) ProtoMessage() {}

func (x *GetWaitingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWaitingRequest.ProtoReflect.Descriptor instead.
func (*GetWaitingRequest) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{0}
}

type GetWaitingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []string `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *GetWaitingResponse) Reset() {
	*x = GetWaitingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWaitingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWaitingResponse) ProtoMessage() {}

func (x *GetWaitingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWaitingResponse.ProtoReflect.Descriptor instead.
func (*GetWaitingResponse) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{1}
}

func (x *GetWaitingResponse) GetPlayers() []string {
	if x != nil {
		return x.Players
	}
	return nil
}

type GameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Victim string `protobuf:"bytes,2,opt,name=victim,proto3" json:"victim,omitempty"`
}

func (x *GameRequest) Reset() {
	*x = GameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRequest) ProtoMessage() {}

func (x *GameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRequest.ProtoReflect.Descriptor instead.
func (*GameRequest) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{2}
}

func (x *GameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameRequest) GetVictim() string {
	if x != nil {
		return x.Victim
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Role    *MafiaRole `protobuf:"varint,2,opt,name=role,proto3,enum=reverse.MafiaRole,oneof" json:"role,omitempty"`
	Reason  *string    `protobuf:"bytes,3,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchResponse) GetRole() MafiaRole {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return MafiaRole_UNKNOWN
}

func (x *SearchResponse) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type GameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason  *string    `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	Role    *MafiaRole `protobuf:"varint,3,opt,name=role,proto3,enum=reverse.MafiaRole,oneof" json:"role,omitempty"`
}

func (x *GameResponse) Reset() {
	*x = GameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResponse) ProtoMessage() {}

func (x *GameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResponse.ProtoReflect.Descriptor instead.
func (*GameResponse) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{4}
}

func (x *GameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GameResponse) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *GameResponse) GetRole() MafiaRole {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return MafiaRole_UNKNOWN
}

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*Event_Connect
	//	*Event_Disconnect
	//	*Event_GameStarted
	//	*Event_GameInterrupted
	//	*Event_HelloMessage
	//	*Event_Ping
	//	*Event_AskSearch
	//	*Event_AskVote
	//	*Event_AskKill
	//	*Event_DayStarted
	//	*Event_NightStarted
	//	*Event_GameFinished
	Data isEvent_Data `protobuf_oneof:"data"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{6}
}

func (m *Event) GetData() isEvent_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Event) GetConnect() *PersonEvent {
	if x, ok := x.GetData().(*Event_Connect); ok {
		return x.Connect
	}
	return nil
}

func (x *Event) GetDisconnect() *PersonEvent {
	if x, ok := x.GetData().(*Event_Disconnect); ok {
		return x.Disconnect
	}
	return nil
}

func (x *Event) GetGameStarted() *GameStarted {
	if x, ok := x.GetData().(*Event_GameStarted); ok {
		return x.GameStarted
	}
	return nil
}

func (x *Event) GetGameInterrupted() *GameInterrupted {
	if x, ok := x.GetData().(*Event_GameInterrupted); ok {
		return x.GameInterrupted
	}
	return nil
}

func (x *Event) GetHelloMessage() string {
	if x, ok := x.GetData().(*Event_HelloMessage); ok {
		return x.HelloMessage
	}
	return ""
}

func (x *Event) GetPing() *PingMessage {
	if x, ok := x.GetData().(*Event_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *Event) GetAskSearch() *Ask {
	if x, ok := x.GetData().(*Event_AskSearch); ok {
		return x.AskSearch
	}
	return nil
}

func (x *Event) GetAskVote() *Ask {
	if x, ok := x.GetData().(*Event_AskVote); ok {
		return x.AskVote
	}
	return nil
}

func (x *Event) GetAskKill() *Ask {
	if x, ok := x.GetData().(*Event_AskKill); ok {
		return x.AskKill
	}
	return nil
}

func (x *Event) GetDayStarted() *DayStarted {
	if x, ok := x.GetData().(*Event_DayStarted); ok {
		return x.DayStarted
	}
	return nil
}

func (x *Event) GetNightStarted() *NightStarted {
	if x, ok := x.GetData().(*Event_NightStarted); ok {
		return x.NightStarted
	}
	return nil
}

func (x *Event) GetGameFinished() *GameFinished {
	if x, ok := x.GetData().(*Event_GameFinished); ok {
		return x.GameFinished
	}
	return nil
}

type isEvent_Data interface {
	isEvent_Data()
}

type Event_Connect struct {
	Connect *PersonEvent `protobuf:"bytes,1,opt,name=connect,proto3,oneof"`
}

type Event_Disconnect struct {
	Disconnect *PersonEvent `protobuf:"bytes,2,opt,name=disconnect,proto3,oneof"`
}

type Event_GameStarted struct {
	GameStarted *GameStarted `protobuf:"bytes,3,opt,name=game_started,json=gameStarted,proto3,oneof"`
}

type Event_GameInterrupted struct {
	GameInterrupted *GameInterrupted `protobuf:"bytes,4,opt,name=game_interrupted,json=gameInterrupted,proto3,oneof"`
}

type Event_HelloMessage struct {
	HelloMessage string `protobuf:"bytes,5,opt,name=hello_message,json=helloMessage,proto3,oneof"`
}

type Event_Ping struct {
	Ping *PingMessage `protobuf:"bytes,6,opt,name=ping,proto3,oneof"`
}

type Event_AskSearch struct {
	AskSearch *Ask `protobuf:"bytes,7,opt,name=ask_search,json=askSearch,proto3,oneof"`
}

type Event_AskVote struct {
	AskVote *Ask `protobuf:"bytes,8,opt,name=ask_vote,json=askVote,proto3,oneof"`
}

type Event_AskKill struct {
	AskKill *Ask `protobuf:"bytes,9,opt,name=ask_kill,json=askKill,proto3,oneof"`
}

type Event_DayStarted struct {
	DayStarted *DayStarted `protobuf:"bytes,10,opt,name=day_started,json=dayStarted,proto3,oneof"`
}

type Event_NightStarted struct {
	NightStarted *NightStarted `protobuf:"bytes,11,opt,name=night_started,json=nightStarted,proto3,oneof"`
}

type Event_GameFinished struct {
	GameFinished *GameFinished `protobuf:"bytes,12,opt,name=game_finished,json=gameFinished,proto3,oneof"`
}

func (*Event_Connect) isEvent_Data() {}

func (*Event_Disconnect) isEvent_Data() {}

func (*Event_GameStarted) isEvent_Data() {}

func (*Event_GameInterrupted) isEvent_Data() {}

func (*Event_HelloMessage) isEvent_Data() {}

func (*Event_Ping) isEvent_Data() {}

func (*Event_AskSearch) isEvent_Data() {}

func (*Event_AskVote) isEvent_Data() {}

func (*Event_AskKill) isEvent_Data() {}

func (*Event_DayStarted) isEvent_Data() {}

func (*Event_NightStarted) isEvent_Data() {}

func (*Event_GameFinished) isEvent_Data() {}

type GameFinished struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinRole MafiaRole `protobuf:"varint,1,opt,name=win_role,json=winRole,proto3,enum=reverse.MafiaRole" json:"win_role,omitempty"`
}

func (x *GameFinished) Reset() {
	*x = GameFinished{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameFinished) ProtoMessage() {}

func (x *GameFinished) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameFinished.ProtoReflect.Descriptor instead.
func (*GameFinished) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{7}
}

func (x *GameFinished) GetWinRole() MafiaRole {
	if x != nil {
		return x.WinRole
	}
	return MafiaRole_UNKNOWN
}

type DayStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DayNum       int32  `protobuf:"varint,1,opt,name=day_num,json=dayNum,proto3" json:"day_num,omitempty"`
	KilledVictim string `protobuf:"bytes,2,opt,name=killed_victim,json=killedVictim,proto3" json:"killed_victim,omitempty"`
}

func (x *DayStarted) Reset() {
	*x = DayStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DayStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayStarted) ProtoMessage() {}

func (x *DayStarted) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayStarted.ProtoReflect.Descriptor instead.
func (*DayStarted) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{8}
}

func (x *DayStarted) GetDayNum() int32 {
	if x != nil {
		return x.DayNum
	}
	return 0
}

func (x *DayStarted) GetKilledVictim() string {
	if x != nil {
		return x.KilledVictim
	}
	return ""
}

type NightStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NightNum int32 `protobuf:"varint,1,opt,name=night_num,json=nightNum,proto3" json:"night_num,omitempty"`
}

func (x *NightStarted) Reset() {
	*x = NightStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NightStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NightStarted) ProtoMessage() {}

func (x *NightStarted) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NightStarted.ProtoReflect.Descriptor instead.
func (*NightStarted) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{9}
}

func (x *NightStarted) GetNightNum() int32 {
	if x != nil {
		return x.NightNum
	}
	return 0
}

type PingMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingMessage) Reset() {
	*x = PingMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMessage) ProtoMessage() {}

func (x *PingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMessage.ProtoReflect.Descriptor instead.
func (*PingMessage) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{10}
}

type PersonEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PersonName string `protobuf:"bytes,1,opt,name=personName,proto3" json:"personName,omitempty"`
}

func (x *PersonEvent) Reset() {
	*x = PersonEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonEvent) ProtoMessage() {}

func (x *PersonEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonEvent.ProtoReflect.Descriptor instead.
func (*PersonEvent) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{11}
}

func (x *PersonEvent) GetPersonName() string {
	if x != nil {
		return x.PersonName
	}
	return ""
}

type GameStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []string  `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Role    MafiaRole `protobuf:"varint,2,opt,name=role,proto3,enum=reverse.MafiaRole" json:"role,omitempty"`
}

func (x *GameStarted) Reset() {
	*x = GameStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStarted) ProtoMessage() {}

func (x *GameStarted) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStarted.ProtoReflect.Descriptor instead.
func (*GameStarted) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{12}
}

func (x *GameStarted) GetPlayers() []string {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameStarted) GetRole() MafiaRole {
	if x != nil {
		return x.Role
	}
	return MafiaRole_UNKNOWN
}

type GameInterrupted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *GameInterrupted) Reset() {
	*x = GameInterrupted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInterrupted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInterrupted) ProtoMessage() {}

func (x *GameInterrupted) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInterrupted.ProtoReflect.Descriptor instead.
func (*GameInterrupted) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{13}
}

func (x *GameInterrupted) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Ask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default string `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
}

func (x *Ask) Reset() {
	*x = Ask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mafia_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ask) ProtoMessage() {}

func (x *Ask) ProtoReflect() protoreflect.Message {
	mi := &file_mafia_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ask.ProtoReflect.Descriptor instead.
func (*Ask) Descriptor() ([]byte, []int) {
	return file_mafia_proto_rawDescGZIP(), []int{14}
}

func (x *Ask) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

var File_mafia_proto protoreflect.FileDescriptor

var file_mafia_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72,
	0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x57, 0x61, 0x69,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x39, 0x0a, 0x0b, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x69, 0x63, 0x74, 0x69, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x76, 0x69, 0x63, 0x74, 0x69, 0x6d, 0x22, 0x88, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x4d, 0x61, 0x66, 0x69,
	0x61, 0x52, 0x6f, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x1b, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x22, 0x86, 0x01, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x2b, 0x0a, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73,
	0x65, 0x2e, 0x4d, 0x61, 0x66, 0x69, 0x61, 0x52, 0x6f, 0x6c, 0x65, 0x48, 0x01, 0x52, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x87, 0x05, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72,
	0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x36, 0x0a,
	0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x39, 0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x65,
	0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65,
	0x64, 0x48, 0x00, 0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64,
	0x12, 0x45, 0x0a, 0x10, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x75,
	0x70, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x65, 0x76,
	0x65, 0x72, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x75,
	0x70, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0f, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x72, 0x75, 0x70, 0x74, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x0d, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0c, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a,
	0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72,
	0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x2d, 0x0a, 0x0a, 0x61, 0x73,
	0x6b, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x41, 0x73, 0x6b, 0x48, 0x00, 0x52, 0x09,
	0x61, 0x73, 0x6b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x29, 0x0a, 0x08, 0x61, 0x73, 0x6b,
	0x5f, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x65,
	0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x41, 0x73, 0x6b, 0x48, 0x00, 0x52, 0x07, 0x61, 0x73, 0x6b,
	0x56, 0x6f, 0x74, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x61, 0x73, 0x6b, 0x5f, 0x6b, 0x69, 0x6c, 0x6c,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x2e, 0x41, 0x73, 0x6b, 0x48, 0x00, 0x52, 0x07, 0x61, 0x73, 0x6b, 0x4b, 0x69, 0x6c, 0x6c, 0x12,
	0x36, 0x0a, 0x0b, 0x64, 0x61, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x44,
	0x61, 0x79, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x64, 0x61, 0x79,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x3c, 0x0a, 0x0d, 0x6e, 0x69, 0x67, 0x68, 0x74,
	0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x3c, 0x0a, 0x0d, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x66, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72,
	0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3d, 0x0a, 0x0c, 0x47,
	0x61, 0x6d, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x08, 0x77,
	0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x4d, 0x61, 0x66, 0x69, 0x61, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x07, 0x77, 0x69, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x4a, 0x0a, 0x0a, 0x44, 0x61,
	0x79, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x61, 0x79, 0x5f,
	0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x61, 0x79, 0x4e, 0x75,
	0x6d, 0x12, 0x23, 0x0a, 0x0d, 0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x5f, 0x76, 0x69, 0x63, 0x74,
	0x69, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x64,
	0x56, 0x69, 0x63, 0x74, 0x69, 0x6d, 0x22, 0x2b, 0x0a, 0x0c, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x5f,
	0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x69, 0x67, 0x68, 0x74,
	0x4e, 0x75, 0x6d, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x2d, 0x0a, 0x0b, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x4f, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x26, 0x0a, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72,
	0x73, 0x65, 0x2e, 0x4d, 0x61, 0x66, 0x69, 0x61, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x22, 0x29, 0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x72,
	0x75, 0x70, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x1f, 0x0a,
	0x03, 0x41, 0x73, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2a, 0x3e,
	0x0a, 0x09, 0x4d, 0x61, 0x66, 0x69, 0x61, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x41, 0x46, 0x49,
	0x41, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x49, 0x56, 0x49, 0x4c, 0x49, 0x41, 0x4e, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x48, 0x45, 0x52, 0x49, 0x46, 0x46, 0x10, 0x03, 0x2a, 0x21,
	0x0a, 0x0a, 0x4d, 0x61, 0x66, 0x69, 0x61, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x09, 0x0a, 0x05,
	0x41, 0x4c, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45, 0x41, 0x44, 0x10,
	0x01, 0x32, 0xf1, 0x02, 0x0a, 0x05, 0x4d, 0x61, 0x66, 0x69, 0x61, 0x12, 0x38, 0x0a, 0x08, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73,
	0x65, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0e, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x4b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x69, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1a, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x35, 0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x72, 0x65, 0x76,
	0x65, 0x72, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x04, 0x4b, 0x69, 0x6c,
	0x6c, 0x12, 0x14, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73,
	0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x37, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x14, 0x2e, 0x72, 0x65, 0x76,
	0x65, 0x72, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x09, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x44, 0x61, 0x79, 0x12, 0x14, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x72,
	0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1d, 0x5a, 0x1b, 0x73, 0x6f, 0x61, 0x5f, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d,
	0x61, 0x66, 0x69, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mafia_proto_rawDescOnce sync.Once
	file_mafia_proto_rawDescData = file_mafia_proto_rawDesc
)

func file_mafia_proto_rawDescGZIP() []byte {
	file_mafia_proto_rawDescOnce.Do(func() {
		file_mafia_proto_rawDescData = protoimpl.X.CompressGZIP(file_mafia_proto_rawDescData)
	})
	return file_mafia_proto_rawDescData
}

var file_mafia_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mafia_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_mafia_proto_goTypes = []interface{}{
	(MafiaRole)(0),             // 0: reverse.MafiaRole
	(MafiaState)(0),            // 1: reverse.MafiaState
	(*GetWaitingRequest)(nil),  // 2: reverse.GetWaitingRequest
	(*GetWaitingResponse)(nil), // 3: reverse.GetWaitingResponse
	(*GameRequest)(nil),        // 4: reverse.GameRequest
	(*SearchResponse)(nil),     // 5: reverse.SearchResponse
	(*GameResponse)(nil),       // 6: reverse.GameResponse
	(*RegisterRequest)(nil),    // 7: reverse.RegisterRequest
	(*Event)(nil),              // 8: reverse.Event
	(*GameFinished)(nil),       // 9: reverse.GameFinished
	(*DayStarted)(nil),         // 10: reverse.DayStarted
	(*NightStarted)(nil),       // 11: reverse.NightStarted
	(*PingMessage)(nil),        // 12: reverse.PingMessage
	(*PersonEvent)(nil),        // 13: reverse.PersonEvent
	(*GameStarted)(nil),        // 14: reverse.GameStarted
	(*GameInterrupted)(nil),    // 15: reverse.GameInterrupted
	(*Ask)(nil),                // 16: reverse.Ask
}
var file_mafia_proto_depIdxs = []int32{
	0,  // 0: reverse.SearchResponse.role:type_name -> reverse.MafiaRole
	0,  // 1: reverse.GameResponse.role:type_name -> reverse.MafiaRole
	13, // 2: reverse.Event.connect:type_name -> reverse.PersonEvent
	13, // 3: reverse.Event.disconnect:type_name -> reverse.PersonEvent
	14, // 4: reverse.Event.game_started:type_name -> reverse.GameStarted
	15, // 5: reverse.Event.game_interrupted:type_name -> reverse.GameInterrupted
	12, // 6: reverse.Event.ping:type_name -> reverse.PingMessage
	16, // 7: reverse.Event.ask_search:type_name -> reverse.Ask
	16, // 8: reverse.Event.ask_vote:type_name -> reverse.Ask
	16, // 9: reverse.Event.ask_kill:type_name -> reverse.Ask
	10, // 10: reverse.Event.day_started:type_name -> reverse.DayStarted
	11, // 11: reverse.Event.night_started:type_name -> reverse.NightStarted
	9,  // 12: reverse.Event.game_finished:type_name -> reverse.GameFinished
	0,  // 13: reverse.GameFinished.win_role:type_name -> reverse.MafiaRole
	0,  // 14: reverse.GameStarted.role:type_name -> reverse.MafiaRole
	7,  // 15: reverse.Mafia.Register:input_type -> reverse.RegisterRequest
	2,  // 16: reverse.Mafia.GetWaitingRoom:input_type -> reverse.GetWaitingRequest
	4,  // 17: reverse.Mafia.Vote:input_type -> reverse.GameRequest
	4,  // 18: reverse.Mafia.Kill:input_type -> reverse.GameRequest
	4,  // 19: reverse.Mafia.Search:input_type -> reverse.GameRequest
	4,  // 20: reverse.Mafia.FinishDay:input_type -> reverse.GameRequest
	8,  // 21: reverse.Mafia.Register:output_type -> reverse.Event
	3,  // 22: reverse.Mafia.GetWaitingRoom:output_type -> reverse.GetWaitingResponse
	6,  // 23: reverse.Mafia.Vote:output_type -> reverse.GameResponse
	6,  // 24: reverse.Mafia.Kill:output_type -> reverse.GameResponse
	6,  // 25: reverse.Mafia.Search:output_type -> reverse.GameResponse
	6,  // 26: reverse.Mafia.FinishDay:output_type -> reverse.GameResponse
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_mafia_proto_init() }
func file_mafia_proto_init() {
	if File_mafia_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mafia_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWaitingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWaitingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameFinished); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DayStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NightStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInterrupted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mafia_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mafia_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_mafia_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_mafia_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*Event_Connect)(nil),
		(*Event_Disconnect)(nil),
		(*Event_GameStarted)(nil),
		(*Event_GameInterrupted)(nil),
		(*Event_HelloMessage)(nil),
		(*Event_Ping)(nil),
		(*Event_AskSearch)(nil),
		(*Event_AskVote)(nil),
		(*Event_AskKill)(nil),
		(*Event_DayStarted)(nil),
		(*Event_NightStarted)(nil),
		(*Event_GameFinished)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mafia_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mafia_proto_goTypes,
		DependencyIndexes: file_mafia_proto_depIdxs,
		EnumInfos:         file_mafia_proto_enumTypes,
		MessageInfos:      file_mafia_proto_msgTypes,
	}.Build()
	File_mafia_proto = out.File
	file_mafia_proto_rawDesc = nil
	file_mafia_proto_goTypes = nil
	file_mafia_proto_depIdxs = nil
}
